### PR TITLE
Add template support for Bulma css framework

### PR DESCRIPTION
**Pull request by ribanez7**
Bulma is gaining popularity between the flexbox css frameworks. Here it is the template support for the pagination component based on the documentation http://bulma.io/documentation/components/pagination/

### CODE REVIEW

**Comment by yuki24** [comment]
This looks great! One thing though, [we are going to deprecate haml and slim](http://www.yukinishijima.net/2017/01/14/kaminari-1-0-0.html#the-e-haml-slim-options-for-rails-g-kaminari-views-have-been-deprecated) in the next major kaminari release to get rid of a burden to maintain these templates that maintainers are unfamiliar with. Would you mind removing haml/slim?

**Comment by ribanez7** [comment]
Hi @yuki24 , sure, I will remove them.

**Comment by ribanez7** [comment]
Done ;)

**Comment by yuki24** [comment]
looks great, thank you!

**Pull request merged**
