### PR TITLE
Add gap to bootstrap4

### PR DESCRIPTION
**Pull request by anduonghien**
## Config ##

`config.outer_window = 1`

### Before ###

screen shot 2017-06-14 at 11 35 53 pm

### After ###

screen shot 2017-06-14 at 11 35 22 pm

### CODE REVIEW

**Comment by yuki24** [comment]
* Could you provide a screenshot for before/after?
 * haml/slim templates are deprecated and we don't keep them up-to-date any more. Would you mind excluding the changes to those templates?

**Comment by anduonghien** [comment]
@yuki24 Sure.

## Config ##

`config.outer_window = 1`

## Screen shoot ##

### Before ###

screen shot 2017-06-14 at 11 35 53 pm

### After ###

screen shot 2017-06-14 at 11 35 22 pm

## Haml/Slim Template issue ##

I already take a look on another theme folder, and inside `bootstrap4 theme` folder, all of that have `haml/slim` extension, so to keep everything need to be the same, I think I can keep it on mine PR. How do you think?

**Comment by yuki24** [comment]
@anduonghien Thanks for the screenshot. It looks great. Starting the next minor release, kaminari will show deprecation warnings. In the next major release, haml/slim templates will be removed entirely. For more details, please read [this blog post](http://www.yukinishijima.net/2017/01/14/kaminari-1-0-0.html#the-e-haml-slim-options-for-rails-g-kaminari-views-have-been-deprecated).

**Comment by yuki24** [comment]
I realized that this is not a new theme, so I'm 👍 with keeping the erb/haml/slim templates in sync. Thanks!

**Pull request merged**
