### PR TITLE
Adds Tailwind CSS theme

### PR DESCRIPTION
**Pull request by tonidezman**
Hi,

if you need me to add slim and haml templates please let me know.

Screen Shot 2019-09-25 at 06 45 04

### CODE REVIEW

**Comment by mattrw89** [comment]
Thank you so much!

**Comment by yuki24** [comment]
I love Tailwind CSS and would love to merge this in. But if we do this... where did these UI components come from? Tailwind CSS itself is just a set of utility classes and they do not provide high-level components. The Tailwind UI is a paid product (which we can't add due to the licensing reasons.)

@tonidezman Did you made the components yourself, or you actually took them from somewhere else? I would really like to make sure there is no copyright issues here.

**Comment by bobbrodie** [comment]
@yuki24 Sorry to just jump into a random thread here, but I think I might have some context. Tailwind UI was previously an additional bundle that had to be added to projects in addition to Tailwind CSS, but they've gotten rid of that so now Tailwind UI is effectively a site that you can pay to have access to pre-built component inspiration that can be copied / pasted into your own project (not a lawyer, but do use base Tailwind CSS and Tailwind UI). This appears to use base Tailwind CSS classes (and Tailwind is now included with Rails 7), so this addition from @tonidezman feels quite fitting.

**Comment by braindeaf** [comment]
Thank you, just what I needed.

**Comment by yuki24** [comment]
I personally would love to merge, but there needs to be some clarifications around what the copyright situation is about this change.

To be 100% clear, I personally do use Tailwind CSS on a daily-basis and also do have the paid Tailwind UI license, so I am fully aware of the technical details and the licensing model there. It is still unclear to me where the proposed change in this PR came from, and we can't merge this PR unless @tonidezman gives us clarifications on it.

**Comment by rodrigoargumedo** [comment]
Tailwind CSS is open-sourced as [MIT licensed](https://github.com/tailwindlabs/tailwindcss/blob/next/LICENSE). I don't think there is a legal issue with that license in mind and it should be good to merge, imo. Hence, a chunk of the CSS classes came from the Tailwind CSS documentation.

Some examples:
[Example 1](https://tailwindcss.com/docs/font-weight)
[Example 2](https://tailwindcss.com/docs/flex)
[Example 3](https://tailwindcss.com/docs/justify-content)

**Comment by bendangelo** [comment]
Can this be merged?

**Comment by yuki24** [comment]
I will have to close this issue as this conversation isn't going anywhere.

Tailwind CSS (not to be confused with Tailwind UI, it's a different thing) itself is never a design system, it's just an implementation detail. We will not merge PRs with the name "Tailwind." However, we would be happy to merge PRs for adding open source Tailwind-based design systems, such as [Flowbite](https://flowbite.com/docs/components/pagination/) and [preline](https://preline.co/docs/pagination.html).

Hosting templates with the name "tailwind" is hugely confusing due to the existence of [Tailwind UI](https://tailwindui.com/) (again, different thing from Tailwind CSS) and it may imply that we are hosting proprietary code in our code base, which we definitely do not want to. We have also never heard back from @tonidezman, so I don't think we are very productive on this thread any more.

**Pull request closed without merging**
