### PR TITLE
Foundation v6 Theme

### PR DESCRIPTION
**Pull request by niels**
This adds ERB, HAML, and SLIM templates for version 6 of the ZURB Foundation framework: http://foundation.zurb.com/sites/docs/pagination.html.

Please note that the ERB and SLIM templates have been automatically converted and are untested.

### CODE REVIEW

**Comment by seuros** [comment]
what the difference between old version and this one ?

**Comment by niels** [comment]
Visually?

Old:
old

Old Hover:
old-hover

New:
new

New Hover:
new-hower

**Comment by seuros** [comment]
not visually. in the markup. 
i did just a quick check, and it seem they are the same.

**Comment by niels** [comment]
`> diff -r foundation foundation6`

```diff
diff -r foundation/app/views/kaminari/_first_page.html.slim foundation6/app/views/kaminari/_first_page.html.slim
2,3c2
<   = link_to_unless(current_page.first?,
<                    raw(t 'views.pagination.first'), url, :remote => remote)
---
>   = link_to_unless current_page.first?, raw(t 'views.pagination.first'), url, :remote => remote
diff -r foundation/app/views/kaminari/_gap.html.erb foundation6/app/views/kaminari/_gap.html.erb
1,3c1
< <li class="unavailable">
<   <%= link_to raw(t 'views.pagination.truncate'), '#' %>
< </li>
---
> <li aria-hidden="true" class="ellipsis"></li>
diff -r foundation/app/views/kaminari/_gap.html.haml foundation6/app/views/kaminari/_gap.html.haml
1,2c1
< %li.unavailable
<   = link_to raw(t 'views.pagination.truncate'), '#'
---
> %li.ellipsis{ :"aria-hidden" => "true" }
diff -r foundation/app/views/kaminari/_gap.html.slim foundation6/app/views/kaminari/_gap.html.slim
1,2c1
< li.unavailable
<   = link_to raw(t 'views.pagination.truncate'), '#'
---
> li.ellipsis  aria-hidden=("true" ) 
diff -r foundation/app/views/kaminari/_last_page.html.slim foundation6/app/views/kaminari/_last_page.html.slim
2,3c2
<   = link_to_unless(current_page.last?,
<                    raw(t 'views.pagination.last'), url, { :remote => remote })
---
>   = link_to_unless current_page.last?, raw(t 'views.pagination.last'), url, {:remote => remote}
diff -r foundation/app/views/kaminari/_next_page.html.slim foundation6/app/views/kaminari/_next_page.html.slim
2,4c2
<   = link_to_unless(current_page.last?,
<                    raw(t 'views.pagination.next'),
<                    url, :rel => 'next', :remote => remote)
---
>   = link_to_unless current_page.last?, raw(t 'views.pagination.next'), url, :rel => 'next', :remote => remote
diff -r foundation/app/views/kaminari/_page.html.erb foundation6/app/views/kaminari/_page.html.erb
2c2,6
<   <%= link_to page, page.current? ? '#' : url, {:remote => remote, :rel => page.next? ? 'next' : page.prev? ? 'prev' : nil} %>
---
>   <% if page.current? %>
>     <%= page %>
>   <% else %>
>     <%= link_to page, url, {:remote => remote, :rel => page.next? ? 'next' : page.prev? ? 'prev' : nil} %>
>   <% end %>
diff -r foundation/app/views/kaminari/_page.html.haml foundation6/app/views/kaminari/_page.html.haml
2c2,5
<   = link_to page, page.current? ? '#' : url, {:remote => remote, :rel => page.next? ? 'next' : page.prev? ? 'prev' : nil}
---
>   - if page.current?
>     = page
>   - else
>     = link_to page, url, {:remote => remote, :rel => page.next? ? 'next' : page.prev? ? 'prev' : nil}
diff -r foundation/app/views/kaminari/_page.html.slim foundation6/app/views/kaminari/_page.html.slim
1,4c1,5
< li{class="#{'current' if page.current?}"}
<   = link_to(page, page.current? ? '#' : url,
<            { :remote => remote,
<               :rel => page.next? ? 'next' : page.prev? ? 'prev' : nil })
---
> li class: "#{'current' if page.current?}" 
>   - if page.current?
>     = page
>   - else
>     = link_to page, url, {:remote => remote, :rel => page.next? ? 'next' : page.prev? ? 'prev' : nil}
diff -r foundation/app/views/kaminari/_paginator.html.erb foundation6/app/views/kaminari/_paginator.html.erb
1,17c1,15
< <%= paginator.render do -%>
<   <div class="pagination-centered">
<     <ul class="pagination">
<       <%= first_page_tag unless current_page.first? %>
<       <%= prev_page_tag unless current_page.first? %>
<       <% each_page do |page| -%>
<         <% if page.left_outer? || page.right_outer? || page.inside_window? -%>
<           <%= page_tag page %>
<         <% elsif !page.was_truncated? -%>
<           <%= gap_tag %>
<         <% end -%>
<       <% end -%>
<       <%= next_page_tag unless current_page.last? %>
<       <%= last_page_tag unless current_page.last? %>
<     </ul>
<   </div>
< <% end -%>
---
> <%= paginator.render do %>
>   <ul aria-label="Pagination" class="pagination" role="pagination">
>     <%= first_page_tag unless current_page.first? %>
>     <%= prev_page_tag unless current_page.first? %>
>     <% each_page do |page| %>
>       <% if page.left_outer? || page.right_outer? || page.inside_window? %>
>         <%= page_tag page %>
>       <% elsif !page.was_truncated? %>
>         <%= gap_tag %>
>       <% end %>
>     <% end %>
>     <%= next_page_tag unless current_page.last? %>
>     <%= last_page_tag unless current_page.last? %>
>   </ul>
> <% end %>
diff -r foundation/app/views/kaminari/_paginator.html.haml foundation6/app/views/kaminari/_paginator.html.haml
2,12c2,11
<   .pagination-centered
<     %ul.pagination
<       = first_page_tag unless current_page.first?
<       = prev_page_tag unless current_page.first?
<       - each_page do |page|
<         - if page.left_outer? || page.right_outer? || page.inside_window?
<           = page_tag page
<         - elsif !page.was_truncated?
<           = gap_tag
<       = next_page_tag unless current_page.last?
<       = last_page_tag unless current_page.last?
---
>   %ul.pagination{ :role => "pagination", :"aria-label" => "Pagination" }
>     = first_page_tag unless current_page.first?
>     = prev_page_tag unless current_page.first?
>     - each_page do |page|
>       - if page.left_outer? || page.right_outer? || page.inside_window?
>         = page_tag page
>       - elsif !page.was_truncated?
>         = gap_tag
>     = next_page_tag unless current_page.last?
>     = last_page_tag unless current_page.last?
diff -r foundation/app/views/kaminari/_paginator.html.slim foundation6/app/views/kaminari/_paginator.html.slim
2,12c2,11
<   .pagination-centered
<     ul.pagination
<       == first_page_tag unless current_page.first?
<       == prev_page_tag unless current_page.first?
<       - each_page do |page|
<         - if page.left_outer? || page.right_outer? || page.inside_window?
<           == page_tag page
<         - elsif !page.was_truncated?
<           == gap_tag
<       == next_page_tag unless current_page.last?
<       == last_page_tag unless current_page.last?
---
>   ul.pagination  role="pagination" aria-label=("Pagination" ) 
>     = first_page_tag unless current_page.first?
>     = prev_page_tag unless current_page.first?
>     - each_page do |page|
>       - if page.left_outer? || page.right_outer? || page.inside_window?
>         = page_tag page
>       - elsif !page.was_truncated?
>         = gap_tag
>     = next_page_tag unless current_page.last?
>     = last_page_tag unless current_page.last?
diff -r foundation/app/views/kaminari/_prev_page.html.slim foundation6/app/views/kaminari/_prev_page.html.slim
2,4c2
<   = link_to_unless(current_page.first?,
<                    raw(t 'views.pagination.previous'),
<                    url, :rel => 'prev', :remote => remote)
---
>   = link_to_unless current_page.first?, raw(t 'views.pagination.previous'), url, :rel => 'prev', :remote => remote
diff -r foundation/README.md foundation6/README.md
1c1
< # Pagination theme for [Zurb Foundation](http://foundation.zurb.com)
---
> # Pagination theme for [Zurb Foundation 6.2.0](http://foundation.zurb.com)
3c3,4
< With support for:
---
> This theme follows [the documented mark-up](http://foundation.zurb.com/sites/docs/pagination.html)
> for version 6.2.0.
5,6c6,17
< - erb
< - haml
\ No newline at end of file
---
> ## Supported template engines:
> 
> - erb (untested)
> - [haml](http://haml.info)
> - [hamlit](https://github.com/k0kubun/hamlit)
> - [slim](http://slim-lang.com/) (untested)
> 
> ## Tips
> 
> - The pagination is not centered by default. To render the pagination centered,
>   simply add the `text-centered` class to the `ul` or a wrapping container, or
>   apply a `text-align: center` style as per [the documentation](http://foundation.zurb.com/sites/docs/pagination.html#centered).
```

**Comment by seuros** [comment]
Thanks. 
Can you rename the foundation folder to foundation5 and keep the current version without versioning ?

**Comment by niels** [comment]
Like so?

**Comment by seuros** [comment]
Yes. Thank you. :green_heart:

**Comment by niels** [comment]
Thank *you* for the quick response(s)! :+1:

**Pull request merged**
