### PR TITLE
Dev codyhouse template 1

### PR DESCRIPTION
**Pull request by guinslym**
On branch (dev_codyhouse_template_1) I added the first Codyhouse pagination template: [Codyhouse -1](http://codyhouse.co/demo/pagination/index.html)

### CODE REVIEW

**Comment by seuros** [comment]
could you provide slim and haml template aswell ?

**Comment by guinslym** [comment]
yes ... I'll do it over the weekend.
Thanks

**Comment by guinslym** [comment]
Hi @seuros I would like to cancel (close) my pull request. I realize that Codyhouse is not a css framework (bootstrap/ foundation...) so users have to create their own stylesheets and by doing so, seems so me it easier for the user to create it self a pagination stylesheet from scratch.

**Comment by seuros** [comment]
fine, thanks for your contribution.

**Pull request closed without merging**
