### PR TITLE
Adding Bourbon Refills styles

### PR DESCRIPTION
**Pull request by mmontalvo**

### CODE REVIEW

**Comment by yuki24** [comment]
Could you also add erb and slim templates?

**Comment by mmontalvo** [comment]
Yep!

**Comment by mmontalvo** [comment]
Updated with erb and slim templates

**Comment by yuki24** [comment]
Could you squash the second commit into the first one?

**Comment by mmontalvo** [comment]
Done

**Comment by yuki24** [comment]
Thanks!

**Comment by mmontalvo** [comment]
:smile:

**Pull request merged**
